name: CustomNameplatesAddon
version: '${version}'
main: dev.vacariu.customnameplatesaddon.CustomNameplatesAddon
api-version: '1.20'
depend: ["CustomNameplates"]
commands:
  me:
    description: Send a bubble chat message.
    permission: customnameplatesaddon.me
    permission-message: You do not have permission!
    usage: /<command> [message]
